apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tps-forvalteren
  namespace: default
  labels:
    team: registre
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
  port: 8080
  ingresses:
    - https://tps-forvalteren.nais.preprod.local
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  readiness:
    path: /internal/isReady
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1500m
      memory: 2048Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/tps-forvalteren/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/dev/config/tpsforvalteren_q1
        mountPath: /var/run/secrets/nais.io/dbPath
      - kvPath: /oracle/data/dev/creds/tpsforvalteren_q1-user
        mountPath: /var/run/secrets/nais.io/db
      - kvPath: /serviceuser/data/dev/srvtps-forvalteren
        mountPath: /var/run/secrets/nais.io/srvtpsf
      - kvPath: /serviceuser/data/dev/srvssolinux
        mountPath: /var/run/secrets/nais.io/ldap
