package no.nav.tps.forvalteren.service.command.tps.skdmelding.skdparam.utils;

import org.springframework.stereotype.Service;

/*
    Generert fra "Landkoder TPS FELLES og TSS 20170209.xlsx" - "TPS Felles"
 */
@Service
public class StatsborgerskapEncoder {

    public String encode(String statsborgerskap) {
        if (statsborgerskap == null) {
            return "000";
        }

        switch (statsborgerskap) {
        case "???":
            return "990";
        case "ABW":
            return "657";
        case "AFG":
            return "404";
        case "AGO":
            return "204";
        case "AIA":
            return "660";
        case "ALA":
            return "860";
        case "ALB":
            return "111";
        case "AND":
            return "114";
        case "ANT":
            return "656";
        case "ARE":
            return "426";
        case "ARG":
            return "705";
        case "ARM":
            return "406";
        case "ASM":
            return "802";
        case "ATF":
            return "628";
        case "ATG":
            return "603";
        case "AUS":
            return "805";
        case "AUT":
            return "153";
        case "AZE":
            return "407";
        case "BDI":
            return "216";
        case "BEL":
            return "112";
        case "BEN":
            return "229";
        case "BFA":
            return "393";
        case "BGD":
            return "410";
        case "BGR":
            return "113";
        case "BHR":
            return "409";
        case "BHS":
            return "605";
        case "BIH":
            return "155";
        case "BLM":
            return "687";
        case "BLR":
            return "120";
        case "BLZ":
            return "604";
        case "BMU":
            return "606";
        case "BOL":
            return "710";
        case "BRA":
            return "715";
        case "BRB":
            return "602";
        case "BRN":
            return "416";
        case "BTN":
            return "412";
        case "BVT":
            return "875";
        case "BWA":
            return "205";
        case "CAF":
            return "337";
        case "CAN":
            return "612";
        case "CCK":
            return "808";
        case "CHE":
            return "141";
        case "CHL":
            return "725";
        case "CHN":
            return "484";
        case "CIV":
            return "239";
        case "CMR":
            return "270";
        case "COD":
            return "279";
        case "COG":
            return "278";
        case "COK":
            return "809";
        case "COL":
            return "730";
        case "COM":
            return "220";
        case "CPV":
            return "273";
        case "CRI":
            return "616";
        case "CSK":
            return "142";
        case "CUB":
            return "620";
        case "CXR":
            return "807";
        case "CYM":
            return "613";
        case "CYP":
            return "500";
        case "CZE":
            return "158";
        case "DDR":
            return "151";
        case "DEU":
            return "144";
        case "DJI":
            return "250";
        case "DMA":
            return "622";
        case "DNK":
            return "101";
        case "DOM":
            return "624";
        case "DZA":
            return "203";
        case "ECU":
            return "735";
        case "EGY":
            return "249";
        case "ERI":
            return "241";
        case "ESH":
            return "304";
        case "ESP":
            return "137";
        case "EST":
            return "115";
        case "ETH":
            return "246";
        case "FIN":
            return "103";
        case "FJI":
            return "811";
        case "FLK":
            return "740";
        case "FRA":
            return "117";
        case "FRO":
            return "104";
        case "FSM":
            return "826";
        case "GAB":
            return "254";
        case "GBR":
            return "139";
        case "GEO":
            return "430";
        case "GGY":
            return "162";
        case "GHA":
            return "260";
        case "GIB":
            return "118";
        case "GIN":
            return "264";
        case "GLP":
            return "631";
        case "GMB":
            return "256";
        case "GNB":
            return "266";
        case "GNQ":
            return "235";
        case "GRC":
            return "119";
        case "GRD":
            return "629";
        case "GRL":
            return "102";
        case "GTM":
            return "632";
        case "GUF":
            return "745";
        case "GUM":
            return "817";
        case "GUY":
            return "720";
        case "HKG":
            return "436";
        case "HMD":
            return "870";
        case "HND":
            return "644";
        case "HRV":
            return "122";
        case "HTI":
            return "636";
        case "HUN":
            return "152";
        case "IDN":
            return "448";
        case "IMN":
            return "164";
        case "IND":
            return "444";
        case "IOT":
            return "213";
        case "IRL":
            return "121";
        case "IRN":
            return "456";
        case "IRQ":
            return "452";
        case "ISL":
            return "105";
        case "ISR":
            return "460";
        case "ITA":
            return "123";
        case "JAM":
            return "648";
        case "JOR":
            return "476";
        case "JPN":
            return "464";
        case "KAZ":
            return "480";
        case "KEN":
            return "276";
        case "KGZ":
            return "502";
        case "KHM":
            return "478";
        case "KIR":
            return "815";
        case "KNA":
            return "677";
        case "KOR":
            return "492";
        case "KWT":
            return "496";
        case "LAO":
            return "504";
        case "LBN":
            return "508";
        case "LBR":
            return "283";
        case "LBY":
            return "286";
        case "LCA":
            return "678";
        case "LIE":
            return "128";
        case "LKA":
            return "424";
        case "LSO":
            return "281";
        case "LTU":
            return "136";
        case "LUX":
            return "129";
        case "LVA":
            return "124";
        case "MAC":
            return "510";
        case "MAF":
            return "686";
        case "MAR":
            return "303";
        case "MCO":
            return "130";
        case "MDA":
            return "138";
        case "MDG":
            return "289";
        case "MDV":
            return "513";
        case "MEX":
            return "652";
        case "MHL":
            return "835";
        case "MKD":
            return "156";
        case "MLI":
            return "299";
        case "MLT":
            return "126";
        case "MMR":
            return "420";
        case "MNG":
            return "516";
        case "MNP":
            return "840";
        case "MOZ":
            return "319";
        case "MRT":
            return "306";
        case "MSR":
            return "654";
        case "MTQ":
            return "650";
        case "MUS":
            return "307";
        case "MWI":
            return "296";
        case "MYS":
            return "512";
        case "MYT":
            return "322";
        case "NAM":
            return "308";
        case "NCL":
            return "833";
        case "NER":
            return "309";
        case "NFK":
            return "822";
        case "NGA":
            return "313";
        case "NIC":
            return "664";
        case "NIU":
            return "821";
        case "NLD":
            return "127";
        case "NOR":
            return "000";
        case "NPL":
            return "528";
        case "NRU":
            return "818";
        case "NZL":
            return "820";
        case "OMN":
            return "520";
        case "PAK":
            return "534";
        case "PAN":
            return "668";
        case "PCN":
            return "828";
        case "PER":
            return "760";
        case "PHL":
            return "428";
        case "PLW":
            return "839";
        case "PNG":
            return "827";
        case "POL":
            return "131";
        case "PRI":
            return "685";
        case "PRK":
            return "488";
        case "PRT":
            return "132";
        case "PRY":
            return "755";
        case "PYF":
            return "814";
        case "QAT":
            return "540";
        case "REU":
            return "323";
        case "ROU":
            return "133";
        case "RUS":
            return "140";
        case "RWA":
            return "329";
        case "SAU":
            return "544";
        case "SDN":
            return "356";
        case "SEN":
            return "336";
        case "SGP":
            return "548";
        case "SGS":
            return "865";
        case "SHN":
            return "209";
        case "SJM":
            return "744";
        case "SLB":
            return "806";
        case "SLE":
            return "339";
        case "SLV":
            return "672";
        case "SMR":
            return "134";
        case "SOM":
            return "346";
        case "SPM":
            return "676";
        case "STP":
            return "333";
        case "SUN":
            return "135";
        case "SUR":
            return "765";
        case "SVK":
            return "157";
        case "SVN":
            return "146";
        case "SWE":
            return "106";
        case "SWZ":
            return "357";
        case "SYC":
            return "338";
        case "SYR":
            return "564";
        case "TCA":
            return "681";
        case "TCD":
            return "373";
        case "TGO":
            return "376";
        case "THA":
            return "568";
        case "TJK":
            return "550";
        case "TKL":
            return "829";
        case "TKM":
            return "552";
        case "TON":
            return "813";
        case "TTO":
            return "680";
        case "TUN":
            return "379";
        case "TUR":
            return "143";
        case "TUV":
            return "816";
        case "TWN":
            return "432";
        case "TZA":
            return "369";
        case "UGA":
            return "386";
        case "UKR":
            return "148";
        case "UMI":
            return "819";
        case "URY":
            return "770";
        case "USA":
            return "684";
        case "UZB":
            return "554";
        case "VAT":
            return "154";
        case "VCT":
            return "679";
        case "VEN":
            return "775";
        case "VGB":
            return "608";
        case "VIR":
            return "601";
        case "VNM":
            return "575";
        case "VUT":
            return "812";
        case "WAK":
            return "831";
        case "WLF":
            return "832";
        case "WSM":
            return "830";
        case "XXK":
            return "161";
        case "XXX":
            return "980";
        case "YEM":
            return "578";
        case "ZAF":
            return "359";
        case "ZMB":
            return "389";
        case "ZWE":
            return "326";
        case "349":
            return "349";
        case "546":
            return "546";
        case "556":
            return "556";
        case "669":
            return "669";
        case "YUG":
            return "925";
        case "PSE":
            return "524";
        case "TLS":
            return "537";
        case "SCG":
            return "125";
        case "MNE":
            return "160";
        case "SRB":
            return "159";
        case "BES":
            return "659";
        case "CUW":
            return "661";
        case "JEY":
            return "163";
        case "SSD":
            return "355";
        case "SXM":
            return "658";
        default:
            return "000";
        }

    }
}
