server.port: 8050

application:
  descriptiveName: tps-forvalteren
  name: tps-forvalteren
  version: 1

tps:
  forvalteren:
    production:
      mode: false

consumers:
  testnav-adresse-service:
    url: https://testnav-adresse-service.dev.intern.nav.no
    name: testnav-adresse-service
    cluster: dev-gcp
    namespace: dolly