--------------------------------------------------
-- S A M P L E  D A T A  FO R  D E M O  O N L Y --
--------------------------------------------------
INSERT INTO T_PERSON (PERSON_ID, IDENT, IDENTTYPE, KJONN, FORNAVN, MELLOMNAVN, ETTERNAVN, KORTNAVN, OPPRETTET_DATO, OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
VALUES (100000000, '12345678910', 'FNR', 'M', 'Ola', 'O', 'Nordmann', 'Ola O Nordmann', CURRENT_TIMESTAMP, 'Z990485',CURRENT_TIMESTAMP, 'Z990485');

INSERT INTO T_PERSON (PERSON_ID, IDENT, IDENTTYPE, KJONN, FORNAVN, ETTERNAVN, KORTNAVN, OPPRETTET_DATO, OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
VALUES (100000001, '33345678910', 'FNR', 'K', 'Kari', 'Nordmann', 'Kari Nordmann', CURRENT_TIMESTAMP, 'Z990485', CURRENT_TIMESTAMP, 'Z990485');

INSERT INTO T_PERSON (PERSON_ID, IDENT, IDENTTYPE, KJONN, FORNAVN, MELLOMNAVN, ETTERNAVN, KORTNAVN, OPPRETTET_DATO, OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
VALUES (100000002, '55545678910', 'FNR', 'M', 'Martin', '', 'Aas', 'Martin Aas', CURRENT_TIMESTAMP, 'Z990485', CURRENT_TIMESTAMP, 'Z990485');

INSERT INTO T_PERSON (PERSON_ID, IDENT, IDENTTYPE, KJONN, FORNAVN, MELLOMNAVN, ETTERNAVN, KORTNAVN, OPPRETTET_DATO, OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
VALUES (100000003, '66645678910', 'FNR', 'K', 'Linn', 'Therese', 'Nilsen', 'Linn Therese Nilsen', CURRENT_TIMESTAMP, 'Z990485', CURRENT_TIMESTAMP, 'Z990485');