ALTER TABLE T_PERSON
ADD FOEDE_KOMMUNE_LAND  VARCHAR2(4);

ALTER TABLE T_PERSON
ADD EGEN_ANSATT_DATO_FOM  TIMESTAMP;
ALTER TABLE T_PERSON
ADD EGEN_ANSATT_DATO_TOM  TIMESTAMP;

ALTER TABLE T_PERSON
ADD TYPE_SIKKERHETSTILTAK   VARCHAR2(4);
ALTER TABLE T_PERSON
ADD SIKKERHETSTILTAK_DATO_FOM   TIMESTAMP;
ALTER TABLE T_PERSON
ADD SIKKERHETSTILTAK_DATO_TOM   TIMESTAMP;
ALTER TABLE T_PERSON
ADD BESKR_SIKKERHETSTILTAK VARCHAR2(50);

ALTER TABLE T_VERGEMAAL
ADD VERGEMAAL_SENDT VARCHAR2(1);