
--CREATE TABLE T_RELASJON_TYPE (
 --   RELASJON_TYPE_ID NUMBER(2) NOT NULL,
  --  TYPE_NAME        VARCHAR(20)
--);

CREATE TABLE T_RELASJON (
    RELASJON_ID NUMBER(9) NOT NULL,
    PERSON_RELASJON_ID NUMBER(9) NOT NULL,
    PERSON_RELASJON_MED_ID NUMBER(9) NOT NULL,
    RELASJON_TYPE_KODE NUMBER(2) NOT NULL
);

---------------------------------------------------
-- P R I M A R Y   K E Y   C O N S T R A I N T S --
---------------------------------------------------
ALTER TABLE T_RELASJON ADD CONSTRAINT T_RELASJON_ID_PK PRIMARY KEY (RELASJON_ID);

---------------------------------------------------
-- F O R E I G N   K E Y   C O N S T R A I N T S --
---------------------------------------------------
ALTER TABLE T_RELASJON ADD CONSTRAINT PERSON_RELASJON_ID_FK FOREIGN KEY (PERSON_RELASJON_ID) REFERENCES T_PERSON(PERSON_ID);

ALTER TABLE T_RELASJON ADD CONSTRAINT PERSON_RELASJON_MED_ID_FK FOREIGN KEY (PERSON_RELASJON_MED_ID) REFERENCES T_PERSON(PERSON_ID);


-----------------------
-- S E Q U E N C E S --
-----------------------
CREATE SEQUENCE T_RELASJON_SEQ          START WITH 100000000;

-----------------------
-- I N S E R T --
-----------------------
--INSERT INTO T_RELASJON_TYPE VALUES (1, 'Ugift');
--INSERT INTO T_RELASJON_TYPE VALUES (2, 'Gift');
--INSERT INTO T_RELASJON_TYPE VALUES (3, 'Enke/-mann');
--INSERT INTO T_RELASJON_TYPE VALUES (4, 'Skilt');
--INSERT INTO T_RELASJON_TYPE VALUES (5, 'Separert');
--INSERT INTO T_RELASJON_TYPE VALUES (6, 'Registrert partner');


