ALTER TABLE T_PERSON
ADD UTVANDRET_TIL_LAND VARCHAR2(2);
ALTER TABLE T_PERSON
ADD REGISTRERT_UTVANDR_DATO   TIMESTAMP;
ALTER TABLE T_PERSON
ADD FLYTTET_TIL_LAND_DATO   TIMESTAMP;

ALTER TABLE T_PERSON
ADD SIVILSTAND VARCHAR2(1) NOT NULL;

ALTER TABLE T_PERSON
ADD INNVANDRET_FRA_LAND VARCHAR2(3) NOT NULL;