ALTER TABLE T_PERSON
  DROP (
  REGISTRERT_UTVANDR_DATO,
  FLYTTET_TIL_LAND_DATO
);

ALTER TABLE T_PERSON
  ADD (
  STATSBORGERSKAP_REGDATO DATE,
  INNVANDRET_FRA_LAND_FLYTTEDATO DATE,
  INNVANDRET_FRA_LAND_REGDATO DATE,
  UTVANDRET_TIL_LAND_FLYTTEDATO DATE,
  UTVANDRET_TIL_LAND_REGDATO DATE
);
