ALTER TABLE T_PERSONMAL MODIFY FODT_ETTER TIMESTAMP;
ALTER TABLE T_PERSONMAL MODIFY FODT_ETTER TIMESTAMP;
ALTER TABLE T_PERSONMAL MODIFY FODT_FOR TIMESTAMP;
ALTER TABLE T_PERSONMAL MODIFY SPESREG_DATO TIMESTAMP;
ALTER TABLE T_PERSONMAL MODIFY DOEDSDATO TIMESTAMP;
ALTER TABLE T_PERSONMAL MODIFY GATE_FLYTTEDATO_FRA TIMESTAMP;
ALTER TABLE T_PERSONMAL MODIFY GATE_FLYTTEDATO_TIL TIMESTAMP;
ALTER TABLE T_PERSONMAL MODIFY POST_FLYTTEDATO_FRA TIMESTAMP;
ALTER TABLE T_PERSONMAL MODIFY POST_FLYTTEDATO_TIL TIMESTAMP;

ALTER TABLE T_PERSONMAL
  ADD (
  STATSBORGERSKAP_REGDATO TIMESTAMP,
  INNVANDRET_FRA_LAND_FLYTTEDATO TIMESTAMP,
  INNVANDRET_FRA_LAND_REGDATO TIMESTAMP,
  UTVANDRET_TIL_LAND VARCHAR2(3),
  UTVANDRET_TIL_LAND_FLYTTEDATO TIMESTAMP,
  UTVANDRET_TIL_LAND_REGDATO TIMESTAMP,
  EGEN_ANSATT_DATO_FOM TIMESTAMP,
  EGEN_ANSATT_DATO_TOM TIMESTAMP,
  TYPE_SIKKERHETSTILTAK TIMESTAMP,
  SIKKERHETSTILTAK_DATO_FOM TIMESTAMP,
  SIKKERHETSTILTAK_DATO_TOM TIMESTAMP,
  BESKR_SIKKERHETSTILTAK VARCHAR2(50),
  IDENT_TYPE VARCHAR2(3) DEFAULT 'FNR' NOT NULL,
  ANTALL_IDENTER NUMBER(4) DEFAULT 1 NOT NULL
  );