-----------------------------
-- A L T E R   T A B L E S --
-----------------------------
ALTER TABLE T_PERSON
  ADD MAALFORM VARCHAR2(2) DEFAULT 'NB';

ALTER TABLE T_PERSON
  MODIFY SIVILSTAND VARCHAR2(4);

-----------------------------
-- M I G R A T E   D A T A --
-----------------------------
UPDATE T_PERSON
SET MAALFORM = 'NB';

UPDATE T_PERSON
SET SIVILSTAND = 'NULL'
WHERE SIVILSTAND = '0';
UPDATE T_PERSON
SET SIVILSTAND = 'UGIF'
WHERE SIVILSTAND = '1';
UPDATE T_PERSON
SET SIVILSTAND = 'GIFT'
WHERE SIVILSTAND = '2';
UPDATE T_PERSON
SET SIVILSTAND = 'ENKE'
WHERE SIVILSTAND = '3';
UPDATE T_PERSON
SET SIVILSTAND = 'SKIL'
WHERE SIVILSTAND = '4';
UPDATE T_PERSON
SET SIVILSTAND = 'SEPR'
WHERE SIVILSTAND = '5';
UPDATE T_PERSON
SET SIVILSTAND = 'REPA'
WHERE SIVILSTAND = '6';
UPDATE T_PERSON
SET SIVILSTAND = 'SEPA'
WHERE SIVILSTAND = '7';
UPDATE T_PERSON
SET SIVILSTAND = 'SKPA'
WHERE SIVILSTAND = '8';
UPDATE T_PERSON
SET SIVILSTAND = 'GJPA'
WHERE SIVILSTAND = '9';

COMMIT;
