-----------------------------
-- M I G R A T E   D A T A --
-----------------------------
UPDATE T_PERSON
SET SPESREG = 'VABO'
WHERE SPESREG = '0';
UPDATE T_PERSON
SET SPESREG = 'URIK'
WHERE SPESREG = '1';
UPDATE T_PERSON
SET SPESREG = 'MILI'
WHERE SPESREG = '2';
UPDATE T_PERSON
SET SPESREG = 'SVAL'
WHERE SPESREG = '3';
UPDATE T_PERSON
SET SPESREG = 'KLIE'
WHERE SPESREG = '4';
UPDATE T_PERSON
SET SPESREG = 'UFB'
WHERE SPESREG = '5';
UPDATE T_PERSON
SET SPESREG = 'SPSF'
WHERE SPESREG = '6';
UPDATE T_PERSON
SET SPESREG = 'SPFO'
WHERE SPESREG = '7';
UPDATE T_PERSON
SET SPESREG = 'PEND'
WHERE SPESREG = '8';

COMMIT;