-----------------
-- T A B L E S --
-----------------
CREATE TABLE T_TPS_AVSPILLER (
  BESTILLING_ID NUMBER(9)      NOT NULL,
  PERIODE_FRA   DATE           NOT NULL,
  PERIODE_TIL   DATE           NOT NULL,
  KILDE_KOE     VARCHAR2(30)   NOT NULL,
  UTLOEP_KOE    VARCHAR2(30)   NOT NULL,
  FORMAT        VARCHAR2(15)   NOT NULL,
  REQUEST       VARCHAR2(4000) NOT NULL,
  ANTALL        NUMBER(9)      NOT NULL,
  TIDSPUNKT     DATE           NOT NULL,
  FERDIG        VARCHAR2(1)    NOT NULL,
  AVBRUTT       VARCHAR2(1)    NOT NULL
);

CREATE TABLE T_TPS_AVSPILLER_PROGRESS (
  PROGRESS_ID   NUMBER(9)     NOT NULL,
  BESTILLING_ID NUMBER(9)     NOT NULL,
  INDEKS_NR     NUMBER(9)     NOT NULL,
  MELDING_NR    NUMBER(9)     NOT NULL,
  TIDSPUNKT     DATE          NOT NULL,
  SEND_STATUS   VARCHAR2(100) NOT NULL
);

---------------------------------------------------
-- P R I M A R Y   K E Y   C O N S T R A I N T S --
---------------------------------------------------
ALTER TABLE T_TPS_AVSPILLER
  ADD CONSTRAINT T_TPS_AVSPILLER_PK PRIMARY KEY (BESTILLING_ID);
ALTER TABLE T_TPS_AVSPILLER_PROGRESS
  ADD CONSTRAINT T_TPS_AVSPILLER_PROGRESS_PK PRIMARY KEY (PROGRESS_ID);

---------------------------------------------------
-- F O R E I G N   K E Y   C O N S T R A I N T S --
---------------------------------------------------
ALTER TABLE T_TPS_AVSPILLER_PROGRESS
  ADD CONSTRAINT BESTILLING_ID_FK FOREIGN KEY (BESTILLING_ID) REFERENCES T_TPS_AVSPILLER (BESTILLING_ID);

-----------------------
-- S E Q U E N C E S --
-----------------------
CREATE SEQUENCE T_TPS_AVSPILLER_SEQ
  START WITH 1;
CREATE SEQUENCE T_TPS_AVSPILLER_PROGRESS_SEQ
  START WITH 1;